### ISSUE TITLE
Socialqa Training

### ISSUE THREAD

**Issue by IslamMohamedMosaad** [ari9dam/McQueen#21]
Hello there,
I have tried to train socialqa but while run run_model_social.sh.
It crashed because "atomic_knowledge_sentences.txt" file not exit.

Could you please show how to generate it?
and Is it possible to publish trained models ?!

**Comment by pratyay-banerjee** [comment]
Hi please find the link to the sentences:
https://drive.google.com/file/d/1pRtaxpnROX1ZmosIkJO6peTUig4Ud9ye/view?usp=sharing

There is a link to a doc showing the parameters for the trained models.

**Comment by IslamMohamedMosaad** [comment]
Thanks.
